name: CI

on:
  push:
    tags:
      - 'v*'  
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Backend
      run: cd backend && yarn && mkdir out
    - name: Install Frontend
      run: cd frontend && yarn
    - name: Build frontend
      run: cd frontend && yarn run build
    - name: Compile
      run: cd backend && yarn run compile
    - name: Pack 
      run: cd backend && yarn run pack
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: backend/schema-visualization-*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true